# Generated by Django 5.2.5 on 2025-08-06 09:22

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_period_start", django_jalali.db.models.jDateField()),
                ("pay_period_end", django_jalali.db.models.jDateField()),
                ("gross_salary", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "tax_deduction",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "insurance_deduction",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "benefits",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Housing, food, etc.",
                        max_digits=10,
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("net_salary", models.DecimalField(decimal_places=0, max_digits=10)),
                ("issue_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "TEACHER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pay_period_end"],
            },
        ),
        migrations.CreateModel(
            name="TuitionFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("issue_date", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("due_date", django_jalali.db.models.jDateField()),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition_fee",
                        to="enrollment.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[
                            ("ZARINPAL", "Zarinpal"),
                            ("DIGIPAY", "Digipay"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Gateway's transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "ADMIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tuition_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.tuitionfee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("due_date", django_jalali.db.models.jDateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "tuition_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="finance.tuitionfee",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
    ]
