# Generated by Django 5.2.5 on 2025-08-06 09:22

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("syllabus", models.TextField(blank=True, null=True)),
                (
                    "base_tuition_fee",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Base tuition fee for the course",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Group A - Mornings'", max_length=200
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("start_date", django_jalali.db.models.jDateField()),
                ("end_date", django_jalali.db.models.jDateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "days_of_week",
                    models.CharField(
                        help_text="e.g., 'Saturday, Monday'", max_length=100
                    ),
                ),
                (
                    "custom_tuition_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Override course base fee if needed",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "TEACHER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classes",
            },
        ),
    ]
